#!/usr/bin/env python3
"""
emit_css.py — CSS custom properties from the resolved token set.

A pure function of the resolver's production-only output. This file REPLACES the
hand-mirrored :root block that was the original drift source — the website and
the HTML style guide consume it, generated, never hand-edited.

    python3 scripts/emit_css.py            # writes product-design-studio/build/tokens.css
    python3 scripts/emit_css.py --stdout   # print instead
"""
import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from resolve_tokens import Resolver  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "product-design-studio" / "build" / "tokens.css"


def slug(path):
    s = path.replace("_", "").replace(".", "-")
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s)
    return s.lower()


def _hex_or_rgba(c):
    if "alpha" in c and c["alpha"] < 1:
        r, g, b = [int(round(x * 255)) for x in c["components"][:3]]
        return f"rgba({r},{g},{b},{c['alpha']})"
    return c["hex"]


def _dim(d):
    v = d["value"]
    v = int(v) if isinstance(v, float) and v.is_integer() else v
    return f"{v}{d['unit']}"


def _num(n):
    return str(int(n) if isinstance(n, float) and n.is_integer() else n)


def _gradient(g):
    stops = ", ".join(f"{_hex_or_rgba(s['color'])} {round(s['position']*100)}%" for s in g["stops"])
    ang = g["angle"]
    return f"linear-gradient({_num(ang)}deg, {stops})"


def _shadow(s):
    return (f"{_dim(s['offsetX'])} {_dim(s['offsetY'])} {_dim(s['blur'])} "
            f"{_dim(s.get('spread', {'value':0,'unit':'px'}))} {_hex_or_rgba(s['color'])}")


def emit(resolved, version=None):
    lines = ["/* GENERATED by scripts/emit_css.py from tokens.json"
             f" v{version} — DO NOT HAND-EDIT. Regenerate with the resolver. */",
             ":root {"]
    for path, e in resolved.items():
        t, v = e["type"], e["value"]
        name = f"  --{slug(path)}"
        if t == "color":
            lines.append(f"{name}: {_hex_or_rgba(v)};")
        elif t == "dimension":
            lines.append(f"{name}: {_dim(v)};")
        elif t == "number":
            lines.append(f"{name}: {_num(v)};")
        elif t == "fontFamily":
            fam = ", ".join((f"'{x}'" if " " in x else x) for x in v)
            lines.append(f"{name}: {fam};")
        elif t == "gradient":
            lines.append(f"{name}: {_gradient(v)};")
        elif t == "shadow":
            lines.append(f"{name}: {_shadow(v)};")
        elif t == "typography":
            fam = ", ".join((f"'{x}'" if " " in x else x) for x in v["fontFamily"])
            lines.append(f"{name}-font-family: {fam};")
            lines.append(f"{name}-font-weight: {v['fontWeight']};")
            if v.get("fontSize"):
                lines.append(f"{name}-font-size: {_dim(v['fontSize'])};")
            if v.get("lineHeight") is not None:
                lines.append(f"{name}-line-height: {_num(v['lineHeight'])};")
            if v.get("letterSpacing"):
                lines.append(f"{name}-letter-spacing: {_dim(v['letterSpacing'])};")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()
    r = Resolver()
    css = emit(r.resolve("production"), r.version)
    if args.stdout:
        sys.stdout.write(css)
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(css)
        print(f"wrote {OUT}  ({len(css.splitlines())} lines)")


if __name__ == "__main__":
    main()
